const sampleData = [
  {
    name: '박유진',
    job: '프로덕트 디자이너',
    company: '숙명여자대학교',
    phone: '010-0000-1111',
    email: 'yj@wellet.co.kr',
    tel: '81-2-222-1234',
    address: '서울시 용산구',
    imageUrl: '',
    category: '비즈니스',
    memo: '내일 미팅',
  },
  {
    name: '한은영',
    job: '프론트엔드 개발자',
    company: '숙명여자대학교',
    phone: '010-1111-2222',
    email: 'ey@wellet.co.kr',
    tel: '81-2-222-2345',
    address: '서울시 용산구',
    imageUrl: '',
    category: '비즈니스',
    memo: '',
  },
  {
    name: '이영희',
    job: '백엔드 개발자',
    company: 'WELLET Corp.',
    phone: '010-2222-3333',
    email: 'yh@wellet.co.kr',
    tel: '81-2-222-4567',
    address: '서울시 마포구',
    imageUrl: '',
    category: '비즈니스',
    memo: '',
  },
  {
    name: '김현우',
    job: '프론트엔드 개발자',
    company: 'WELLET Corp.',
    phone: '010-3333-4444',
    email: 'hw@wellet.co.kr',
    tel: '81-2-222-5678',
    address: '서울시 성동구',
    imageUrl: '',
    category: '비즈니스',
    memo: '',
  },
  {
    name: '김디공',
    job: '대표',
    company: '다공 부동산',
    phone: '010-4444-5555',
    email: 'dg@wellet.co.kr',
    tel: '81-2-222-6789',
    address: '부산광역시',
    imageUrl: '',
    category: '부동산',
    memo: '',
  },
  {
    name: '홍길동',
    job: '대표 | 공인중개사',
    company: '동네공인중개사',
    phone: '010-5555-6666',
    email: 'gd@wellet.co.kr',
    tel: '81-2-222-7890',
    address: '대전광역시',
    imageUrl: '',
    category: '부동산',
    memo: '',
  },
  {
    name: '김인쇄',
    job: '공인중개사',
    company: '인쇄픽부동산',
    phone: '010-6666-7777',
    email: 'is@wellet.co.kr',
    tel: '81-2-222-8901',
    address: '서울시 강남구',
    imageUrl: '',
    category: '부동산',
    memo: '',
  },
  {
    name: '박대기',
    job: '보도본부 사회팀 / 기자',
    company: 'KBS',
    phone: '010-7777-8888',
    email: 'dk@wellet.co.kr',
    tel: '81-2-222-9012',
    address: '서울시 동작구',
    imageUrl: '',
    category: '방송사',
    memo: '',
  },
  {
    name: '홍길동',
    job: '팀장 / PD',
    company: 'KBS VJ 특공대',
    phone: '010-8888-9999',
    email: 'kd@wellet.co.kr',
    tel: '81-2-222-0123',
    address: '인천광역시',
    imageUrl: '',
    category: '방송사',
    memo: '',
  },
];

export default sampleData;
